# Generated by Django 2.1 on 2019-10-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191030_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=10, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Password'),
        ),
    ]
