# Generated by Django 2.1 on 2019-11-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191030_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10, verbose_name='User')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('post_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
