# Generated by Django 2.1 on 2019-11-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191103_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=1234, max_length=10, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
