# Generated by Django 2.1 on 2019-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_hitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
