# Generated by Django 2.1 on 2019-11-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191105_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitcount',
            name='post',
        ),
        migrations.AddField(
            model_name='hitcount',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
